---
- name: Setup database setting
  ansible.builtin.include_tasks: database/{{ include_file_map[gitea_cfg['database']['DB_TYPE']] }}.yml
  vars:
    include_file_map:
      mariadb: mysql
      mysql: mysql
      postgres: postgres
  when: hedgedoc_cfg[hedgedoc_mode]['db']['host'] | default('localhost') in ['localhost', '127.0.0.1']
