---
- name: add hedgedoc user
  ansible.builtin.user:
    name: "{{ hedgedoc_user }}"
    system: true
- name: create install directory
  ansible.builtin.file:
    path: "{{ hedgedoc_home }}"
    owner: "{{ hedgedoc_user }}"
    group: "{{ hedgedoc_user }}"
    state: directory
    mode: "0755"
