---
- name: Find variable file
  ansible.builtin.set_fact:
    variable_file: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}/{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.os_family }}/{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars
- name: Include variable file
  ansible.builtin.include_vars: "{{ variable_file }}"
  when: variable_file | length > 0
- name: Dependency tasks
  ansible.builtin.import_tasks: dependency.yml
  tags: dependency
- name: Install packages
  ansible.builtin.import_tasks: package.yml
  tags: package
- name: Setup database
  ansible.builtin.import_tasks: database.yml
  tags: database
- name: Create/update setting
  ansible.builtin.import_tasks: setting.yml
  tags: setting
- name: Setup service
  ansible.builtin.import_tasks: service.yml
  tags: service
