---
- name: Install hedgedoc
  become: true
  become_user: "{{ hedgedoc_user }}"
  block:
    - name: Checkout source
      ansible.builtin.git:
        repo: https://github.com/hedgedoc/hedgedoc.git
        dest: "{{ hedgedoc_home }}"
        version: "{{ hedgedoc_version }}"
      register: git_result
    - name: Install dependency packages && build
      when: git_result is changed
      block:
        - name: Install build dependency packages
          ansible.builtin.command:
            cmd: yarn install --frozen-lockfile
            chdir: "{{ hedgedoc_home }}"
        - name: Install dependency packages
          ansible.builtin.command:
            cmd: yarn build
            chdir: "{{ hedgedoc_home }}"
        - name: Install dependency packages
          ansible.builtin.command:
            cmd: yarn install --production=true --frozen-lockfile
            chdir: "{{ hedgedoc_home }}"
