---
- name: Set Install version variable
  when: hedgedoc_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/hedgedoc/hedgedoc/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set hedgedoc_version variable
      ansible.builtin.set_fact:
        hedgedoc_version: "{{ latest_releases.json.tag_name }}"
- name: Setup HedgeDoc
  become: true
  become_user: "{{ hedgedoc_user }}"
  block:
    - name: Install/update HedgeDoc
      ansible.builtin.unarchive:
        src: https://github.com/hedgedoc/hedgedoc/releases/download/{{ hedgedoc_version }}/hedgedoc-{{ hedgedoc_version }}.tar.gz
        dest: "{{ hedgedoc_home }}"
        extra_opts:
          - --strip-components=1
        remote_src: true
      notify: Restart hedgedoc
    # - name: Install HedgeDoc dependency npm packages
    #   community.general.npm:
    #     path: "{{ hedgedoc_home }}"
