---
- name: load default config
  command: cat {{ hedgedoc_home }}/config.json.example
  changed_when: false
  register: result
- name: set default config variable
  set_fact:
    default_hedgedoc_cfg: "{{ result.stdout | from_json }}"
- name: combine hedgedoc config
  set_fact:
    hedgedoc_cfg: "{{ default_hedgedoc_cfg | combine(hedgedoc_cfg, recursive=True) }}"
- name: add/update setting file
  block:
    - name: add/update setting file
      template:
        src: config.json.j2
        dest: "{{ hedgedoc_home }}/config.json"
        mode: "0644"
      register: result
      notify: restart hedgedoc
  become: true
  become_user: "{{ hedgedoc_user }}"
