---
- name: Add/update setting file
  become: true
  become_user: "{{ hedgedoc_user }}"
  block:
    - name: Add/update setting file
      ansible.builtin.template:
        src: config.json.j2
        dest: "{{ hedgedoc_home }}/config.json"
        mode: "0644"
      register: result
      notify: Restart hedgedoc
