---
hedgedoc_cfg:
  production:
    domain: localhost
    # host: localhost
    # port: 3000
    # protocolUseSSL: true
    # urlAddPort: false
    path: /var/run/hedgedoc/hedgedoc.sock
    sessionSecret: "{{ inventory_hostname | hash('sha1') }}"
    db:
      ## dialect: mysql / mariadb / postgres / sqlite
      dialect: mariadb
      host: localhost
      port: 3306
      database: hedgedoc
      username: hedgedoc
      password: hedgedoc_password
