---
- name: Restart hedgedoc
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: hedgedoc
- name: Reload hedgedoc
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: reloaded
    name: hedgedoc
