---
- name: Install database dependency packages(MariaDB)
  ansible.builtin.apt:
    name:
      - mariadb-client
      - mariadb-server
      - libmariadb-dev
      - python{{ ansible_facts.distribution_major_version is version('11', '>=') | ternary('3', '') }}-pymysql
- name: Create database
  community.mysql.mysql_db:
    name: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['database'] }}"
    encoding: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['encoding'] | default('utf8mb4') }}"
    collation: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['collation'] | default('utf8mb4_general_ci') }}"
    login_unix_socket: "{{ mariadb_unix_socket_path | default('/run/mysqld/mysqld.sock') }}"
- name: Create database user
  community.mysql.mysql_user:
    name: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['username'] }}"
    password: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['password'] }}"
    host: "{{ item }}"
    priv: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['database'] }}.*:ALL"
    login_unix_socket: "{{ mariadb_unix_socket_path | default('/run/mysqld/mysqld.sock') }}"
  loop:
    - localhost
    - 127.0.0.1
