---
- name: Install database dependency packages(PostgreSQL)
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2
      - acl
- name: Setup database
  become: true
  become_user: postgres
  block:
    - name: Create database user
      community.postgresql.postgresql_user:
        name: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['username'] }}"
        password: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['password'] }}"
    - name: Create database
      community.postgresql.postgresql_db:
        name: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['database'] }}"
        owner: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['username'] }}"
        encoding: "{{ hedgedoc_cfg[hedgedoc_mode]['db']['encoding'] | default('UTF8') }}"
